### ISSUE TITLE
"Helm Dependency Update" got error message

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#142]
when executing "Helm Dependency Update" we got below output in terminal. To solve this error, we need to run "helm serve" in bash.

Would that be better if the plugin gives a prompt message to remind user ?

![image](https://user-images.githubusercontent.com/4318793/38015872-cb6a20d4-329f-11e8-9293-2d2128431d48.png)

**Comment by bnookala** [comment]
@songkaiape can you `cat` your `requirements.yaml` file and paste it here? I believe that connection refused message is expected to appear - I just ran `helm dependency update` on the phabricator chart to see what would happen:

```
$ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "deis" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading mariadb from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

**Comment by songkaiape** [comment]
@bnookala  Below is my requirement.yaml
```
dependencies:
  - name: redis
    version: 1.1.19
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: mongodb
    version: 0.4.28
    repository: https://kubernetes-charts.storage.googleapis.com
```
