### ISSUE TITLE
Can not apply changes v0.1.9

### ISSUE THREAD

**Issue by earlcoder** [Azure/vscode-kubernetes-tools#218]
After editing a deployment you can not apply your changes. When selecting apply a warning pops up saying "Could not find a valid API object"

![screen shot 2018-05-17 at 12 28 48 pm](https://user-images.githubusercontent.com/24445887/40199397-29d92822-59ce-11e8-8fde-dfef155e8981.png)

**Comment by adamgoose** [comment]
I am also encountering this issue, and will answer your questions.

- Yes, I have a file titled `traefik-deployment.yaml` open and saved.
- YAML, loaded from disk.
- Yes, document is saved!
- No, the document is entirely blank.

Each of the blocks in my yaml file are erroring in the IDE as well:

![](http://d.enge.me/xEC10B+)

```yaml
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
  type: NodePort

```
