### ISSUE TITLE
Detect ContainerPorts on the Pod for Port Forwarding

### ISSUE THREAD

**Issue by bnookala** [Azure/vscode-kubernetes-tools#261]
If a Pod explicitly exposes ports in its definition, we should offer a way for our users to Port Forward to them without having to dig for those ports. 

Example pod yaml that exposes ports:

```yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
