### ISSUE TITLE
Support multi-resources with different schemas YAML files

### ISSUE THREAD

**Issue by victornoel** [Azure/vscode-kubernetes-tools#341]
When opening a k8s YAML file, there can be multiple resources descrtibed in it, separated by `---`.

For example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx
      volumes:
        - name: config-volume
          configMap:
            name: app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config: some config
```

In practice, the editor shows an error saying `Matches multiple schemas when only one must validate.` and not validation happens.

I think that we should be able to validate separately the different resources of a yaml file without problems by considering them as if they were different files.

Even though YAML support is implemented with yaml-language-server, according to the discussion in redhat-developer/yaml-language-server#80, the problem should be solved in the present extension and not there.
