### ISSUE TITLE
AWS EKS cluster gives 'error: You must be logged in to the server (Unauthorized)' error even when kubectl works fine

### ISSUE THREAD

**Issue by derekssmith** [Azure/vscode-kubernetes-tools#402]
I have used this extension in the past with Amazon EKS clusters, however after using the AWS cli to update the kube config file it no longer works.  I followed these instructions: https://docs.aws.amazon.com/eks/latest/userguide/configure-kubectl.html

kubectl works just fine, but when I try to view any of the resources in the extension it gives the following error: `error: You must be logged in to the server (Unauthorized)`

I have multiple AWS profiles on my machine, as well as multiple kubectl contexts.

**Comment by derekssmith** [comment]
@itowlson thanks for the tips!  I was able to figure out my issue.  The problem had to do with the fact that I am using multiple AWS profiles on my machine.  I usually switch what AWS account I am using by running `export $AWS_PROFILE=<profile>`.  

The [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) tool is used to authenticate to AWS IAM and get a token for communicating with the EKS cluster.  When using the `aws eks update-kubeconfig --name cluster_name` command it modifies your kubeconfig file for you, only it doesn't set the `env` variable with the AWS_PROFILE.  When the extension executes it's commands the aws-iam-authenticator doesn't have an AWS_PROFILE to use.

Here is my kubeconfig users node before fix:

```
users:
- name: cluster1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - account1
      command: aws-iam-authenticator
- name: cluster2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - account2
      command: aws-iam-authenticator
```

Here is the updated config with the `AWS_PROFILE` set in the `env`, which fixed the issue.
```
users:
- name: cluster1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - account1
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: account1
- name: cluster2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - account2
      command: aws-iam-authenticator
      env: 
      - name: AWS_PROFILE
        value: account2
```
