### ISSUE TITLE
ConfigMap doesn't allow the value 'Yes' in config values

### ISSUE THREAD

**Issue by tomasaschan** [Azure/vscode-kubernetes-tools#405]
The following config map
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
  bar: 'Yes'
```
has a linting error on the `'Yes'` value, saying `Incorrect type. Expected "string".` I'm assuming it sees the string `yes` and tries to interpret the value as a boolean, but what if I *want* to interpret it as a string? How do I make that not an error?
