### ISSUE TITLE
URI query parameters are not shown in secret preview

### ISSUE THREAD

**Issue by shroudedcode** [Azure/vscode-kubernetes-tools#594]
For some obscure reason query parameters are stripped from URIs when viewing an individual value of a secret through the Clusters panel.

## How to reproduce

1. Create a secret like this and apply it:

```yml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  URI: http://example.com/test?blah=sth
```

2. Reload the Clusters panel.

3. Click on the `test` secret in the tree view. You'll see that the `URI` value has been correctly Base64-encoded:

```yml
data:
  # -> http://example.com/test?blah=sth
  URI: bW9uZ29kYjovL2V4YW1wbGUuY29tL3Rlc3Q/YmxhaD1zdGg=
```

4. Now click on `URI` (the individual value nested inside `test`) in the tree view:

```
mongodb://example.com/test
```

As you can see, the URI does not have any query parameters anymore.
