### ISSUE TITLE
"Kubernetes: Apply" does not do anything

### ISSUE THREAD

**Issue by TimBobkov** [Azure/vscode-kubernetes-tools#60]
I create new test deployment file like:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - command:
            - sh
            - -c
            - while true; do sleep 86400; done
          image: busybox
          name: test
      terminationGracePeriodSeconds: 1
```
Next I run "Kubernetes: Apply" command and nothing is changed...
I expect deployment creation after this command or even error message.
I can manage my cluster (get logs, deployments, pods, etc.) through this extension so I think config is OK and ```kubectl``` is reachable.
Also I have try to open existing deployment, change it and run same command - same effect, nothing is changed.
Maybe I do something wrong?
