### ISSUE TITLE
Extension spawns many copies of kubectl proxy on startup

### ISSUE THREAD

**Issue by jacobwgillespie** [Azure/vscode-kubernetes-tools#619]
When I open up VS Code for the first time and open a Kubernetes YAML file, the Kubernetes extension seems to be spawning **a lot** of instances of `kubectl proxy --port=0` for every Kubernetes API object in the file.

For instance, opening this file (one of `cert-manager`'s resources), results in spawning 28 copies of `kubectl`:

<details>
<summary>cluster-role.yaml</summary>

```yaml
# Challenges controller role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-controller-challenges
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: cert-manager-v0.10.0
rules:
  # Use to update challenge resource status
  - apiGroups: ['certmanager.k8s.io']
    resources: ['challenges', 'challenges/status']
    verbs: ['update']
  # Used to watch challenges, issuer and clusterissuer resources
  - apiGroups: ['certmanager.k8s.io']
    resources: ['challenges', 'issuers', 'clusterissuers']
    verbs: ['get', 'list', 'watch']
  # Need to be able to retrieve ACME account private key to complete challenges
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
  # Used to create events
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'patch']
  # HTTP01 rules
  - apiGroups: ['']
    resources: ['pods', 'services']
    verbs: ['get', 'list', 'watch', 'create', 'delete']
  - apiGroups: ['extensions']
    resources: ['ingresses']
    verbs: ['get', 'list', 'watch', 'create', 'delete', 'update']
  # We require these rules to support users with the OwnerReferencesPermissionEnforcement
  # admission controller enabled:
  # https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
  - apiGroups: ['certmanager.k8s.io']
    resources: ['challenges/finalizers']
    verbs: ['update']
  # DNS01 rules (duplicated above)
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
```

</details>

```bash
$ ps aux | grep kubectl
jacobwgillespie  43516   0.0  0.2  4457000  26244   ??  S     1:25pm   0:00.10 kubectl proxy --port=0
jacobwgillespie  43515   0.0  0.2  4456488  26712   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43514   0.0  0.2  4458572  28016   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43512   0.0  0.2  4449332  28076   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43507   0.0  0.2  4455720  27448   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43506   0.0  0.2  4459352  27796   ??  S     1:25pm   0:00.12 kubectl proxy --port=0
jacobwgillespie  43505   0.0  0.2  4449332  27660   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43504   0.0  0.2  4454952  26996   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43503   0.0  0.2  4447540  27616   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43489   0.0  0.2  4464436  26236   ??  S     1:25pm   0:00.12 kubectl proxy --port=0
jacobwgillespie  43486   0.0  0.2  4456744  26544   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43484   0.0  0.2  4449880  26324   ??  S     1:25pm   0:00.12 kubectl proxy --port=0
jacobwgillespie  43481   0.0  0.2  4448052  27400   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43479   0.0  0.2  4457000  27504   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43476   0.0  0.2  4474176  26348   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43475   0.0  0.2  4459096  26452   ??  S     1:25pm   0:00.12 kubectl proxy --port=0
jacobwgillespie  43474   0.0  0.2  4449064  26500   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43473   0.0  0.2  4448284  26756   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43472   0.0  0.2  4439068  26340   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43470   0.0  0.2  4440908  26648   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43469   0.0  0.2  4449600  26896   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43468   0.0  0.2  4460656  26696   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43524   0.0  0.2  4442444  26692   ??  S     1:25pm   0:00.12 kubectl proxy --port=0
jacobwgillespie  43523   0.0  0.2  4439860  27396   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43521   0.0  0.2  4467544  26432   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43520   0.0  0.2  4449100  26244   ??  S     1:25pm   0:00.12 kubectl proxy --port=0
jacobwgillespie  43519   0.0  0.2  4449856  27456   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
jacobwgillespie  43517   0.0  0.2  4440104  25984   ??  S     1:25pm   0:00.11 kubectl proxy --port=0
```

This appears to be related to the number of resources inside the file, so for instance opening `cert-manager.yaml` from https://github.com/jetstack/cert-manager/releases/download/v0.10.0/cert-manager.yaml, with all resources included, attempts to launch over **430** instances of `kubectl proxy --port=0` before my computer stops responding.

---

Note that this happens when opening a file for the first time, so in terms of reproduction:

1. Open VS Code in a blank state where it doesn't have any open files
2. Everything is okay
3. Open [`cert-manager.yaml`](https://github.com/jetstack/cert-manager/releases/download/v0.10.0/cert-manager.yaml)
4. 100s of `kubectl proxy --port=0` processes appear

I have not dug far into the code, but I would assume that this is related to #583 that loads Swagger API definitions from the live cluster.  I would have expected that code to ensure that only one process is fetching the schema at a time, but perhaps that's missing or something's preventing the cache / mutex from working properly.
