### ISSUE TITLE
Linter shows false mistake in Ingress config

### ISSUE THREAD

**Issue by RafaelAybar** [Azure/vscode-kubernetes-tools#621]
I have the following config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: daas-php-fpm
  namespace: develop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: example.com
    - http:
        paths:
          - path: /
            backend:
              serviceName: php-fpm-nginx
              servicePort: 80
```
Visual Studio Code version: ```1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64 (snap)```

Plugin version: `Kubernetes 1.0.4`
But I see this issue with no reason, as far i know it is configured as official docs says:
![imagen](https://user-images.githubusercontent.com/21227176/65418196-3314a980-ddfc-11e9-85df-3c4b8c478788.png)
