### ISSUE TITLE
targetPort does not accept integer as valid

### ISSUE THREAD

**Issue by brandonkal** [Azure/vscode-kubernetes-tools#632]
targetPort can be an integer, but VSCode reports a linting error that it expected a "string."

```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```
