### ISSUE TITLE
No intellisense with multiple resources in one file

### ISSUE THREAD

**Issue by brandonkal** [Azure/vscode-kubernetes-tools#633]
When multiple resources are in one file (seperated by "---" for instance), no intellisense is available at all.

<details><summary>Example file</summary>
<p>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  hostname: fred
  containers:
  - name: myapp
    image: <Image>
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: <Image>
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
```

</p>
</details>

I've made a note of this [here](https://github.com/Azure/vscode-kubernetes-tools/issues/626#issuecomment-542037029) but because the issue occurs locally as well, I am opening a new issue.
