### ISSUE TITLE
Snippet fills in wrong location

### ISSUE THREAD

**Issue by brandonkal** [Azure/vscode-kubernetes-tools#678]
If you type:
```yaml
apiVersion: v1
kind: Ser
```
You will get a suggestion for the Kubernetes Service snippet. If if it chosen, the YAML is not correct:
```yaml
apiVerion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: cool
spec:
  selector:
    app: cool
  ports:
  - port: 8080
```
As you can see, it fills in the wrong location. Smarter completion is needed here.
