### ISSUE TITLE
breakpoints in vscode not working as expected when debugging in docker container

### ISSUE THREAD

**Issue by mmoron** [Azure/vscode-kubernetes-tools#724]
I'm trying to debug .netcore mvc application running in a docker container with kubernetes.

I've installing `vsdbg` inside a container and run it. Here is my dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["GraphQLApi.csproj", "."]
RUN dotnet restore "GraphQLApi.csproj"
COPY . .
RUN dotnet build "GraphQLApi.csproj" --no-restore -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "GraphQLApi.csproj" --no-restore -c Debug -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Install the dependencies for Visual Studio Remote Debugger
RUN apt-get update && apt-get install -y --no-install-recommends unzip procps

# Install Visual Studio Remote Debugger
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg  

ENTRYPOINT ["dotnet", "GraphQLApi.dll"]
```

and this is my deployment yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: test2
  labels:
    app: test2
spec:
  selector:
    app: test2
  ports:
  - nodePort: 30917
    port: 8082
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  labels:
    app: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: test2
        image: test2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
```

Application starts as expected and I'm running `Kubernetes: Attach (Attach)` in vscode. Debugger is being attached as expected. So far so good. Unfortunately when I hit a breakpoint vscode is not showing correct breakpoints in editor. App is stopped and I can see correct values in Locals, but I can't inspect code connected to a breakpoint. Instead when I click a breakpoint in breakpoints list empty file is shown:

![image](https://user-images.githubusercontent.com/3398332/78285341-dae40000-7520-11ea-81a2-552d192f73f7.png)

Also, when I add breakpoints they are not shown in code editor:

![image](https://user-images.githubusercontent.com/3398332/78285920-07981780-7521-11ea-820c-ba2b876e1123.png)
![image](https://user-images.githubusercontent.com/3398332/78285763-fc44ec00-7520-11ea-895d-cc1944137517.png)

When i debug locally everything works as expected:

![image](https://user-images.githubusercontent.com/3398332/78289828-0d8ef800-7523-11ea-8422-672c277c2a23.png)

Expected behavour:

I should be able to see breakpoints in code editor and inspect values directly in code.
