### ISSUE TITLE
gotpl syntax highlighting doesn't work if any literal text precedes it

### ISSUE THREAD

**Issue by philomory** [Azure/vscode-kubernetes-tools#759]
![image](https://user-images.githubusercontent.com/200123/82719289-dd232a80-9c44-11ea-9b4e-850a3f9878f6.png)

As stated, the highlighting of gotpl (e.g. `{{ ... }}`) blocks doesn't work if it's preceded by any literal text (subsequent literal text seems fine).

Document:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example
  annotations:
    example.com/good: {{ .Values.this_works }}
    example.com/also.good: {{ .Values.so_does_this }}-as-well
    example.com/bad: unfortunately-{{ .Values.this_does_not_work }}
    example.com/also.bad: unfortunately-{{ .Values.this_does_not_work }}-either
```

There's nothing special about the map keys I used; in fact it doesn't have to be a map at all, the same problem occurs if you have a sequence, e.g.
```
example_sequence:
  -  {{ .Values.this_works }}
  - but {{ .Values.this_does_not }}
```

It _does_ work if wrap your template element in double-quotes, though not in single quotes:
```
good: "This {{ .Values.will_work }} fine"
bad: 'This {{ .Values.will_fail }} sadly'
```
