### ISSUE TITLE
Deleting context in extension removes required parts in k8s config

### ISSUE THREAD

**Issue by asampal** [Azure/vscode-kubernetes-tools#783]
To reproduce:

- Set up Docker Desktop in Windows with WSL 2 integration and enable k8s
- In VSCode, install vscode-kubernetes-tools and notice that there are two contexts shown: docker-desktop and docker-for-desktop
- Note that only the docker-desktop context includes child items
- Remove empty context, docker-for-desktop in VSCode by selecting "Delete from kubeconfig" in the context menu of this context
- Go to Windows Terminal and attempt to run "docker" from the command line
- Observe that invoking 'docker` do longer finds the cli client, but instead returns the following:
```
PS C:\Users\adi> docker
unable to resolve docker endpoint: default orchestrator is kubernetes but unable to resolve kubernetes endpoint: invalid configuration: no configuration has been provided
```
- Compare /mnt/c/users/<user>/.kube/config before and after the context removal and note that key elements seem to have been removed

Before:
```
adi@vesuvius:/mnt/c/Users/<****>$ cat .kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EVXhOREEyTlRBMU1Wb1hEVE13TURVeE1qQTJOVEExTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3g4CkRTNm8vZ3hBcHA2WHNEY1BwbitnZnJwRTNxd1RCYVhHVW9JdVNrS25uRDhVNGZRVVVFSGlYWDR2NUo5aDRpVmwKTGZqQTEzUWtLOStVSjdBZlFRTnlpVXJLNCtwZTBaaXZwOUR3STZFbEZDbWVmZUdEbkIvM2ord201NWJrR2x3LwozcFNXNVdmeEUzdkh3ZkhtM2t3WXZMblhoZzdqbldxL1ViSGQ1ZnkrL2NranQ2eXVKOVVCejhHbTgzVDdBVk52Ck9OZG5sNXVrdlZMdVNyQmdTWDYzb2JvazJ5UlE4eGoxV2orSGlXeisvR0tNQUtYOHp5MWx6NFZtZ1krNlRlRWgKYXRuODJtOWhDWHNTM3dVQm92REZMUEVXc0phT2hMMFh1U0FrOXlBTzUxb0c4U2tOaC84dngzTHZ4Q2cxSFBzVgpNb2svZlhaQUMwNEJuOTh0THkwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGNUpMZ1R6WUNxbTZGaHBlOEJIVlpIV3RiQTMKV2Ryb2lRTGR1clJaTzZvblJrODJKMFRxRWkxbTVqdUtYanZFUnQxRFN3VHdsWGJ0VEdSRmpyd1Ardi9uZ3R4OApIdXpURlVrMGZ2UWtmSTJCemZQaW5UbXhLS2toYXhra1Jwa0o5byt6OWpHOWYwb1pZZGg0UW4rSXcrNnBlY2xEClA5SG9ucUpHdlZXWm9ZWkVGUkNLTDlxaWc4cVR0WU4xR2hVcmlBUCtIRHhsWmdvVXk2SkR3emI4Tm9VR3B2VSsKSUlrcmc5c09DWnRvdktUczMwOXQrTlJaQjlqSEJ1SUVWeGZHbUdubjdaczRzeVpoK0hVdEJ0eXJXY202dFZNQgpFZFBWUzk2NncwUjNjcUVLcDFLNy9HdmdENHhJT3NaK3IzWTU1dURJT1dZbXVFT2c0UU9EREtiWENqcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lJQmdMT2tVNllaOGt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBMU1UUXdOalV3TlRGYUZ3MHlNVEEzTURJd056QXhNVFJhTURZeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sc3dHUVlEVlFRREV4SmtiMk5yWlhJdFptOXlMV1JsCmMydDBiM0F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRERZMElyL0g5Z0prM2sKZ0JXOGI2OWFEdGZZakQvTU8xaGpCWkZoWCtRVnNYWW1JZzBKVVlENWJQaEdFRlNVcTNQMENSbEYwbG5zS3NOegphZjdxTHIzRzc0Yml3RE5wMmxuZER5amJxbDU5RkdndFpHQll4Y1I4bVllaTh0UU5wdFErbjdRZEZXSTFFTGYwClV5KzdwTE9BMnltWDlueWd3TEFhTWV6VnQ2SFRMVUxRejRyQjAxWFVKTk1lMGp5eEdtN240M2dtMENBSVFqTkUKZzlqYWdGNy8xclRqZGk4amV5M2tDZlVaOXIvdTFyRU5IMVFTS0YycThtVVdyYjJOMlQzOSsrVDBkNER6RzV2awpXRXA4S05uMzlyTFRKejdneXhjallqL2l3cnRhSzc1RitFNmdZUVdQd0RUVzVkL2tHaEdzTk5DN1RLZm5xTDE0CkRoZUwyVGlKQWdNQkFBR2pKekFsTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTeW9xWjNDVXo4Y3VIdWZ4dDZHQThJU3FHQ2Q5ZlNPRQpGYnJyOUxWTmhDbDJSOVdZWDVBdi9tT0Roczg5bVJjSEJjYS9Xek5GVjJoR1RESjI1d1ZCVHRQZ2c1eTl0cWlOCmNUa3g2ZUgvOXdRdkF6U1ZyemxuWXIzVnRkOTVyNGNySkpKSGh0dXQ4aXJDYkRTaVZmUVJJdWtBRXFRcHRFSkUKeXMwQWZLSHlsUWNJRXdldCtSZlNQQkdxZ0FXTGRKK3llMU1UNGo0eVVNWCt1Y3M5cjFUSHgrR1doaGdQUnRaWApzZUt4L3psUWo4R0JlWVpyRGh3NFY3Z3N3eCtHSG1KMVVRN1VhMnRSNEZMbVc2eVhBL2JZRnVhYTVOUEJCMGI1CkJUSHpOSFpqcWxUdXRqQXQ1d21oMVRWRUJFOU1XQXVndmdGS2NqYjN1cHhUWFBONlBIUkNEUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdzJOQ0sveC9ZQ1pONUlBVnZHK3ZXZzdYMkl3L3pEdFlZd1dSWVYva0ZiRjJKaUlOCkNWR0ErV3o0UmhCVWxLdHo5QWtaUmRKWjdDckRjMm4rNmk2OXh1K0c0c0F6YWRwWjNROG8yNnBlZlJSb0xXUmcKV01YRWZKbUhvdkxVRGFiVVBwKzBIUlZpTlJDMzlGTXZ1NlN6Z05zcGwvWjhvTUN3R2pIczFiZWgweTFDME0rSwp3ZE5WMUNUVEh0SThzUnB1NStONEp0QWdDRUl6UklQWTJvQmUvOWEwNDNZdkkzc3Q1QW4xR2ZhLzd0YXhEUjlVCkVpaGRxdkpsRnEyOWpkazkvZnZrOUhlQTh4dWI1RmhLZkNqWjkvYXkweWMrNE1zWEkySS80c0s3V2l1K1JmaE8Kb0dFRmo4QTAxdVhmNUJvUnJEVFF1MHluNTZpOWVBNFhpOWs0aVFJREFRQUJBb0lCQUJCVnNRZUtZWC9CVkF2QgpaWS9PYW9PRjhDZXJlZjN5REM2akhZZGRnKzBJWEE5T0UzYnUrSEJoMnRQSXM3bUdKL2lEOWpmdklSTnNjOUNuClVPZDFKdXFGeGVvWkZYTkpEUEE5UHpZMkpSWWg2Wis1MzVBc1lJUG1OZis2ZTEzMHo1TzR1RThpSllhNE1oamMKQjRhUmUyeFBaa2ZORkpnLzQ3a2M2V2JvcGovSVNEYlVlZFFYZUpUNURpWk5XSlAxSHhXOHhLWlFwOWswQU9pbwpYVldqWkVBSWEzYzhZTE8vM0lzeitLS28wb2dBU1dodyt5UFhyUjNqNmJTaHpTclZ3ajhvNTROUkYvZjBrV01GCkhPTS9acWFkUjJOelhRSEFwS1NHL2N0cVZUeWJzdWljRXN6WmozNnV0bkt4a1IvaDZwa052K29RSTRZRmh4Z0oKRFJDTUZIRUNnWUVBeFJXZTdMS2c4UkFxcTVMcEdIV3NuNGN3SEgxWENLUFh4RmVBVGNxYW1NanFQc1dtNmlybQpHRlJBTHJabnlrUmdpTXgxK1Z0bHNuaytaZzkzV2xIZ2NsRS90Q055YkswdDJ2SUYralR3TFRyT1R0ZndSRS9GCm5LUGZ1eHpmazE4TzBWdVYvWnQyR0FNT2M4V1pvclluM3N3Vk8zMEdSbkpGMWJNUjZTenBlOTBDZ1lFQS9jdksKbHFhRmU5K0R0Q3NyVHVCNHZkRHdMS2RuSkV0czU0a3k2K3VuRTNuWkFEK05OR3pDSE1FT3l5d0hjNWhMWXNONApYRStPVndTYyt2QVBlZDJYMXZ4WWMxZEducExQcGNYRk5qeDJIeEpLdTRINlcwZUtoNUtqRWZRWFhPdjZPM0dtCmc1L3VPcTNud3NjQmxTK3NSd1BOM1V6WnJIRmRuc0t3Vi9sT0twMENnWUE1eGxqTWNxRVRpZlc0VGx6ZXVzQmMKRTdsYTRMTis2T2o3dWRyMjh3blcrQzhUTDhYNnA1REVXUTVub3psUjVqR1dhTG04MjdvNFU2cWpLSzJJWUxBMwpVdklsMEs1ZWhYWUgxU05EY2ZsbWlQS3Awa3V3K3VHblJiTDBtMFkvWVlKcWhUcTNHYmZJMmp5R1c4cnFGQlFrCkVCZTVWTEZlUFdtVGQrY3NQK3BDVVFLQmdRREkxYnlpREhJeS9VUUdqZWEraTBsZ3cvZGJEcm5DOGVEak5DSFUKcVcxVUx5YjJXRlFRT1VRK1p0T2pHVnRvTVFydXc4bjZHb2FEKzhXUm1laFZRbktHa0xnWnhlVy9WR1AzUlpKegpBZE5qY1NFc1VvWGdON082NXVJZU1lOU8rL25Qa25iM1Q5YkFIcC80OVd3ZU4xUjMrZDJ0a3NQcC91ZmIyeXFhCjQxRGt6UUtCZ1FDVDl5MlY1Yk56YnBOWjk2NnJraGxROUIwdWcrdkpzcGU4eXJob2l5Tkl2MGQ4TGZpWDd5eDEKejByc1Jxay9pVkZJTUhKdnRTcFJIbDNNaXd4aXNxRndnZ1I5RitzdEZIVEx4dkViSE1hbGhkaTg0QlFZZDNBOQo1ZUltNGJ1S016QUhyMXlHVnNGc3h1em1QWXNVTlRkY1lLSEhJaHlPcEpFck8wT2NMU01vU1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

After:
```
adi@vesuvius:/mnt/c/Users/<****>$ cat .kube/config
apiVersion: v1
clusters: []
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users: []
```

- Restore kubeconfig and note that 'docker' invocation from the command-line is restored

System Info:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041

VSCode Info:
Version: 1.47.0-insider (user setup)
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:27:06.804Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

vscode-kubernetes-tools: v 1.2.1
