### ISSUE TITLE
Cannot set kubeconfig with the multiple context config file

### ISSUE THREAD

**Issue by diwap** [Azure/vscode-kubernetes-tools#819]
## Version
Extension Version: v1.2.1

__VS CODE__
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

## Description
Whenever there is only one configuration per file, I can set multiple configuration. However, if I have a single file with multiple context, it doesn't show any cluster information or error.

Below is my sample config file:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: arn:aws:eks:us-east-1:123456:cluster/cluster_name
- cluster:
    certificate-authority-data: 
    server: 
  name: arn:aws:eks:us-east-1:12345:cluster/cluster_name1
- cluster:
    certificate-authority-data: 
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:123456:cluster/cluster_name
    namespace: default
    user: arn:aws:eks:us-east-1:123456:cluster/cluster_name
  name: arn:aws:eks:us-east-1:123456:cluster/cluster_name
- context:
    cluster: arn:aws:eks:us-east-1:12345:cluster/cluster_name1
    namespace: default
    user: arn:aws:eks:us-east-1:12345:cluster/cluster_name1
  name: arn:aws:eks:us-east-1:12345:cluster/cluster_name1
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
current-context: arn:aws:eks:us-east-1:12345:cluster/cluster_name
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:12345:cluster/cluster_name
  user:
    exec:
      apiVersion: v1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - clustername
      command: aws
      env:
      - name: AWS_PROFILE
        value: default
- name: arn:aws:eks:us-east-1:12345:cluster/cluster_name1
  user:
    exec:
      apiVersion: v1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - cluster_name1
      command: aws
      env:
      - name: AWS_PROFILE
        value: default1
- name: docker-desktop
  user:
    client-certificate-data: 
    client-key-data: 
```
