### ISSUE TITLE
Feature request: kustomization support

### ISSUE THREAD

**Issue by haf** [Azure/vscode-kubernetes-tools#824]
It would be great if this extension didn't highlight "errors" when using `kubectl apply -k` or `kustomize build [folder]`.

For example, for a deployment, having a `selector` like:

```yaml
  selector:
    matchLabels:
      app: ksqldb
      component: ksqldb
```

Will be filled out with this kustomize:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

commonLabels:
  app: ksqldb
  component: ksqldb
```
