### ISSUE TITLE
No intelisense for Minio CRD

### ISSUE THREAD

**Issue by arianvp** [Azure/vscode-kubernetes-tools#835]
Intelisense is working for all my CRDs except minio. But I can't figure out why it is not working.

The CRD in question is defined here: https://github.com/minio/operator/blob/master/operator-kustomize/crds/minio.min.io_tenants.yaml

It does seem to include a structured schema; just as the others. But Intelisense is not kicking in

Example config:

```yaml
## MinIO Tenant Definition
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
spec:
  image: minio/minio:RELEASE.2020-10-18T21-54-12Z
  imagePullPolicy: IfNotPresent
  podManagementPolicy: Parallel
  credsSecret:
    name: minio-creds-secret
  zone:
    - servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: "local-path"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  
```
