### ISSUE TITLE
[enhancement request] linter should warn about unpaired double quotes in values.yaml file

### ISSUE THREAD

**Issue by caleb15** [Azure/vscode-kubernetes-tools#845]
**Problem**: someone accidentally left a " in the values.yaml file, like so:

```yaml
jobs:
  foo":
    enabled: true
```

Our templates/template.yaml looks like this:
```yaml
{{- range $name, $details := .Values.jobs }}{{ if $details.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $name }}"
{{- /*
# more stuff
*/ -}}
```

When the chart is rendered with helmfile the " breaks the template, like so:
![image](https://user-images.githubusercontent.com/46505081/101099771-36680100-357a-11eb-8dcf-99d454e63648.png)

**Solution**
Linter warns when there is a unpaired quotation mark in a key

I'm still new to helm so my apologies if this isn't a valid issue.
