### ISSUE TITLE
Snippets: ingress.yaml should use apiVersion: networking.k8s.io/v1

### ISSUE THREAD

**Issue by markszente** [Azure/vscode-kubernetes-tools#901]
Snippet [`ingress.yaml`](https://github.com/Azure/vscode-kubernetes-tools/blob/master/snippets/ingress.yaml) currently uses `apiVersion: extensions/v1beta1`, which is deprecated in v1.14+ (and will be removed in v1.22). It should therefore be replaced with `apiVersion: networking.k8s.io/v1`.

Proposed body for the snippet, in accordance with the [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressservicebackend-v1-networking-k8s-io): 
```
apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ${1:myingress}
    labels:
        name: ${1:myingress}
  spec:
    rules:
    - host: ${2:<Host>}
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: ${3:<Service>}
              port: 
                number: ${4:<Port>}
```
