### ISSUE TITLE
Random Helm Output messages

### ISSUE THREAD

**Issue by afmsavage** [Azure/vscode-kubernetes-tools#907]
In the VSCode output window, there are sometimes very vague errors from the Helm extension that pop up every time you open up a helm based project.  There is no detail around these messages, and I cannot figure out how to turn them off or where the error is coming from.  There is no information in `helm lint` nor in the Problems tab.  Please provide more information about why these are occuring.  Example: 
```
Unexpected characters ().
```

![image](https://user-images.githubusercontent.com/29739267/111165323-e3d0b480-856c-11eb-9dec-9467b17a5409.png)

**Comment by bacongobbler** [comment]
I could only find two locations where that error message can be found:

https://github.com/Azure/vscode-kubernetes-tools/blob/e134027df60019718c2a45e9b3df59d660a08fdb/src/helm.documentProvider.ts#L83-L90

https://github.com/Azure/vscode-kubernetes-tools/blob/929a87c101bbe46d5233f88c37c4868079b88846/src/helm.exec.ts#L417-L424

Can you report back which version of the extension you are using? Thanks

**Comment by afmsavage** [comment]
Chart.yaml is generic, no issues in it that I can see or any `( )` characters.

```
apiVersion: v1
appVersion: "1.0"
name: mina
description: A Helm chart to deploy a 
version: 0.2.0
keywords:
  - m
maintainers:
- name: b
  email: hi@b.co
  url: https://b.co
```

Kubernetes Extension: v1.3.0

**Comment by bacongobbler** [comment]
Hmm... Thanks for the report. I don't know where this error message might be reported from but perhaps other maintainers may know more.

**Comment by itowlson** [comment]
That message is coming via the Helm output logger (defined in `src/logger.ts`.  I can't see anywhere it outputs that message format in the extension, which means it's coming either from Helm itself, via stdout or stderr, or from some other external source such as the YAML extension.  The fact that you see it on load (without running any explicit commands) makes me wonder if it's coming from the completion provider or something... We may need to improve tracing to track it down...

**Comment by thernstig** [comment]
I have seen this issue for a long time, but never reported it. It happens every time I open a repo with Helm where I have the `values.yaml` file open. The output is the same as in the original post: `Unexpected characters ().` (seen in the Output for Helm). The annoying part is that this error actually _opens_ the Output panel automatically, so I have to manually close it every time.

**Comment by afmsavage** [comment]
I think I know why this is occurring in at least my project.  The only place that I have `( )`'s in my chart is in the `serviceMonitor.spec.endpoints.sourceLabels.regex` field where we are using this to ignore certain Prometheus metrics to save cycles.  Not sure if this helps to track this issue down or not.

```yaml
  endpoints:
    - port: {{ .Values.metrics.name }}
      interval: 10s
      metricRelabelings:
      - sourceLabels: [__name__]
        regex: '(Coda_Cryptography.*|Coda_Network_get.*|Coda_Object_lifetime.*|Coda_Scan.*|Coda_Snark.*)'
        action: drop
```

EDIT: Actually I completely missed that I have other parentheses in my statefulSet under a container's `args` field as well.  
```yaml
        args: [
          "daemon",
          "--peer-list-file", "$(PEERLIST_LOCATION)",
          "--block-producer-key", "/keystore/my-wallet",
          "--generate-genesis-proof", "true",
          "--file-log-level", "$(LOG_LEVEL)",
          "--metrics-port", {{ .Values.metrics.port | quote }},
          "--coinbase-receiver", "$(REWARDS_ADDRESS)"
          ]
```
