### ISSUE TITLE
After accepting some completion, the schema of a kubernetes CRD used is changing and thus wrong validation error appears

### ISSUE THREAD

**Issue by apupier** [Azure/vscode-kubernetes-tools#926]
using this CRD: https://github.com/apache/camel-k/blob/9e384110be106b4970af2e967e28e0877fa78359/config/crd/bases/camel.apache.org_kameletbindings.yaml
with this file:
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: bitcoin-to-kafka
spec:
  integration:
```

calling completion and accepting on `flows` is giving a validation error. the schema used is no more the same.

![wrongSchemaCRDUsed](https://user-images.githubusercontent.com/1105127/115238776-5b6ea200-a11e-11eb-8441-324052e52152.gif)
