### ISSUE TITLE
[Question] Helm lint + k8s yaml validation

### ISSUE THREAD

**Issue by MrLuje** [Azure/vscode-kubernetes-tools#947]
You can helm lint/preview a chart to make sure your helm & generated yaml are correct but AFAIK, you can't validate/lint that a resulting deployment.yaml from a chart is a valid deployment resource

See example below :

*deployment.yaml*
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "api.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

            # <---------------- indentation of resources is wrong but is legal yaml
            resources:
              {{- toYaml .Values.resources | nindent 12 }}
```

helm lint is fine with it (and it's ok because it is legal yaml syntax) but it is wrong in term of k8s resource.
Resource is badly indented and should be a container property, not within env property.

Using yaml schema, you should be able to catch this kind of issue (eg: by adding a comment "**yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json**" at the top of this deployement file) but since this is a helm template, it is not seen as valid yaml and everything is reported being wrong.

Question: Is there a built-in way to validate a chart's resource against k8s schemas ? (ideally, without asking an api server about it, so no **install --dry-run**) and even better, to have problems reported directly in vscode validation.
