### ISSUE TITLE
Missing JSON object responses in the log

### ISSUE THREAD

**Issue by cilerler** [Azure/vscode-kubernetes-tools#955]
The cronjob below generates two lines of output 
- **(a)** writes `vscodek8s` 
- **(b)** writes your external IP address as a JSON object like `{"ip":"35.???.???.252"}`

When I look at the output through the extension log viewer, it shows me different result than what I see in the console with `kubectl logs <pod-name>`

![image](https://user-images.githubusercontent.com/385958/119661475-55936d00-bdfe-11eb-8921-9461aa58ab59.png)

### actual result on VSCODE extension

```text
vscodek8s
```

### expected result _(also actual result on console)_
```text
vscodek8s
{"ip":"35.???.???.252"}
```

### sample cronjob to reproduce

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-stop-vscodek8s
  namespace: default
  labels:
    app: cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: job-stop-vscodek8s
            image: google/cloud-sdk:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - -c
            - '
              echo "vscodek8s" && curl -s curl https://api.ipify.org?format=json
              '
```
