### ISSUE TITLE
Lint yells when using 'null' 

### ISSUE THREAD

**Issue by exocode** [Azure/vscode-kubernetes-tools#961]
Hi there, 
no big deal but I like my IDE silent.

 linter is yelling, but `null` and `{}` seems legit for me at this point. 

I have this problem when I use skaffold.dev which generates a Yaml files from my docker-compose.yml files like so:
`skaffold init --compose-file docker-compose.yml` 

Should I post that to the skaffold.dev Team?

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null   # <-- "creationTimestamp (string)"


spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
          resources: {} # <-- ("No resource limits specified for this container - this could starve other processes")
```

regards
