### ISSUE TITLE
The extension falsely reports validation errors in Kustomization patch manifests

### ISSUE THREAD

**Issue by rille111** [Azure/vscode-kubernetes-tools#995]
## Problem description

Can´t ignore / disable or change schema validation on kustomization patch files. The extension believes it's a true kubernetes manifest with all its expections, and validates with the kubernetes schema. Therefore the extension complains that the .yaml patch file doesn´t match the expectations.

## Steps to Reproduce

1. Create a **patch.yaml** file with the following content:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
```
2. Observe the problems in VSCode
![image](https://user-images.githubusercontent.com/1324189/140220417-267748bf-c61c-425c-9a94-3caf62032005.png)

## Expected Behavior

Different schema to validate against, or disable/ignore certain files (like kustomization patches) altogether. 

## Current Behavior

All files get validated according to the kubernetes schema even if kustomization files are meant to not adhere to the schema.

## Relevant installed and enabled extensions

- vscode-kubernetes-tools
- redhat.vscode-yaml (uses https://github.com/redhat-developer/yaml-language-server)
- vscode-eslint
- prettier-vscode
- vscode-docker

## Proposed solutions

1. Allow the extension to be configured with **glob patterns** to ignore validation on certain directories / files. Something like this: https://github.com/redhat-developer/vscode-yaml
2. Or maybe when a `kustomization.yaml` file is detected in the folder, smartly detect the files that are kustomization patches and ignore them
3. A comment in the beginning of a manifest to let the extension know that this is a Kustomization patch and have other rules, or another schema to use. Example:
``` yaml
# kubernetes-is-kustomization-patch: true
# OR
# vscode-kubernetes-tools-ignore-validation: true
# OR something else..
apiVersion: apps/v1
kind: Deployment
```
